### ISSUE TITLE
NPM won't Install the module (Dependency fails to build)

### ISSUE THREAD

**Issue by xIAlexanderIx** [gj/fastify-ws#5]
utf-8-validate it's outdated and throws a 404 during the build

`prebuild-install http 404 https://github.com/websockets/utf-8-validate/releases/download/v3.0.4/utf-8-validate-v3.0.4-node-v64-win32-x64.tar.gz`

That causes to fail the entire installation.

EDIT: The issue is only present on node v10, works fine on the LTS release

**Comment by gj** [comment]
Should be solved by #6.

Thanks for pointing it out @xIAlexanderIx !
